--- # EC2 - Start/Stop/Terminate Module
- hosts: localhost
  connection: local
  remote_user: test
  become: yes
  gather_facts: no
  vars_files:
  - files/awscreds.yml
  tasks:
  - name: Manager state of instance
    ec2:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{aws_region }}"
      instance_ids: i-4a6c9ae5
      state: stopped