---# Gathering EC2 instance facts
- hosts: aws
  connection: ssh
  remote_user: ec2-user
  become:yes
  connection: ssh
  gather_facts: yes
  tasks:
  - name: Gather the Ec2 facts about running instance
    action: ec2_facts
  - name: Conditonal Display of instance type
    debug: msg="This Instance is of type t2.micro"
      when: ansible_ec2_instance_type =='t2.micro'
